### PR TITLE
More authorization skeleton code

### PR DESCRIPTION
**Pull request by Therason**
This adds a lot of the skeleton for logging users in. The login button now calls the `signIn()` function with the credentials provided by the user, however the user will always be successfully logged in. Once we get the DB models established, I will add code to the `authorize()` function to compare the password against the hashed version inside the DB.

The "Other Logins" button was changed to a "Login with Google" button. In the future maybe we could also add a Google icon to the button. I also changed the modal from an editable input to a regular form. I think it would be best to use regular inputs to login, since the user doesn't have to delete/edit the placeholder text.
image
The big things remaining for user authorization stuff is a way for users to sign up, and allowing users using OAuth to sign up.

### CODE REVIEW

**Comment by joelinnn** [comment]
Merge the main branch changes and remake the pull request

**Comment by Therason** [comment]
@joelinnn I don't think a new PR is necessary, as I added commits that resolve the conflicts. Let me know if it works!

**Comment by joelinnn** [comment]
Thats what I meant, sorry for the confusion lol

**Comment by joelinnn** [comment]
Theres a new merge again, check if there are any conflicts with your code first

**Comment by Therason** [comment]
@joelinnn should be fixed now as long as nobody else makes and merges another request

**Review by joelinnn — APPROVED** [review]
Looks solid!

**Pull request merged**
